server:
  port: 8081

spring:
  data:
    rest:
      base-path: /api

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/onlinestore_ohiji
    username: $username
    password: $password
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: $username
    password: $password

    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000