server:
  port: 8081

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error

# cloud-aws 設定
cloud:
  aws:
    credentials:
      use-default-aws-credentials-chain: false
      access-key: AKIA2JUR4PESSGKBHOUC
      #profile-path: D:\Software_development\Project_onlineStore_ohiji\OnlineStore_ohiji_backEnd\.aws\credentials
      #profile-name: test
      instance-profile: true
      secret-key: W69KrNMVzYoqVrCZX9mPwrtVVGsjenBrMHywQ0ox
    region:
      static: ap-northeast-1
      use-default-aws-region-chain: true
      auto: false
    stack:
      auto: false
      enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      base-path: /api
# spring-cloud 設定
  cloud:
    config:
      enabled: true

# JPA 設定
  jpa:
    hibernate:
      ddl-auto: update

# DataBase 設定
  datasource:
    url: jdbc:mysql://mysql-database-ohiiji1.c2p3jxirx1bq.ap-northeast-1.rds.amazonaws.com/onlinestore_ohiji
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

# java-mail 設定
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: ${JAVAMAIL_EMAIL}
    password: ${JAVAMAIL_PW}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000