key:
  hostname:
    frontEnd: "http://reactjsonlinestorefrontend-env.eba-3pthpit7.ap-northeast-1.elasticbeanstalk.com"
    backEnd: "http://springbootonlinestorebackend-env.eba-tfseztpn.ap-northeast-1.elasticbeanstalk.com"

server:
  port: 80

spring:
  data:
    rest:
      base-path: /api
  # spring-cloud 設定
  cloud:
    config:
      enabled: false

  # JPA 設定
  jpa:
    hibernate:
      ddl-auto: update

  # DataBase 設定
  datasource:
    url: database_url
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # java-mail 設定
  mail:
    protocol: smtp
    # 使用 gmail 的 smtp(簡單郵遞傳送協定)
    host: smtp.gmail.com
    port: 465
    username: gmail_username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000