server:
  port: 8081

# cloud-aws 設定
cloud:
  aws:
    region:
      static: ap-northeast-1
    credentials:
      access-key: AKIA2JUR4PESVLEU7JW4
      secret-key: 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

spring:
  data:
    rest:
      base-path: /api
# JPA 設定
  jpa:
    hibernate:
      ddl-auto: update

# DataBase 設定
  datasource:
    url: jdbc:mysql://mysql-database-ohiiji.c2p3jxirx1bq.ap-northeast-1.rds.amazonaws.com/onlinestore_ohiji
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

# java-mail 設定
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: ${JAVAMAIL_EMAIL}
    password: ${JAVAMAIL_PW}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 1000
          timeout: 1000
          writetimeout: 1000