name: Push Image to Docker Hub & Deploy to AWS
on:
  push:
    branches:
      - master
jobs:
  # Checkout and test
  check:
    outputs:
      status: ${{ steps.test.conclusion }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      -
        name: Checkout Latest Repo
        uses: actions/checkout@v2
      -
        id: test
        name: Build and testing Docker images
        run: |
          echo "Build docker images for testing..."
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/springboot_onlinestore_backend-test -f ./Dockerfile.dev .
          echo "Run react tests with built Docker images..."
          docker run -e CI=true ${{ secrets.DOCKER_HUB_USERNAME }}/springboot_onlinestore_backend-test

  # Build and push to Docker Hub
  push_image_to_docker_hub:
    needs: [ check ]
    if: needs.check.outputs.status == 'success'
    outputs:
      status: ${{ steps.push.conclusion }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        id: push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/springboot_onlinestore_backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/springboot_onlinestore_backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/springboot_onlinestore_backend:buildcache,mode=max

  # Deploy to AWS Elastic Beanstalk
  deploy_to_aws:
    needs: [ push_image_to_docker_hub ]
    if: needs.push_image_to_docker_hub.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Latest Repo
        uses: actions/checkout@v2
      -
        name: Generate Deployment Package
        run: zip -r deploy.zip *
      -
        id: current-time
        name: Get timestamp
        uses: gerred/actions/current-time@master
      -
        name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: SpringBoot_onlineStore_backEnd
          environment_name: Springbootonlinestorebackend-env
          version_label: "SpringBoot_onlineStore_backEnd-deployment-${{ steps.current-time.outputs.time }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip